 
    <option value="MASTUJ">MASTUJ</option>
    <option value="WARI">WARI</option>
    <option value="TEMERGARA">TEMERGARA</option>
    <option value="KABAL">KABAL</option>
    <option value="BESHAM">BESHAM</option>
    <option value="KHADOKHAIL">KHADOKHAIL</option>
    <option value="SWAT RANIZAI">SWAT RANIZAI</option>
    <option value="DASSU">DASSU</option>
    <option value="	BALAKOT">BALAKOT</option>
    <option value="JUDBA">JUDBA</option>
    <option value="ALLAI">ALLAI</option>
    <option value="HAVELIAN">HAVELIAN</option>
    <option value="GHAZI">GHAZI</option>
    <option value="TAKHT BHAI">TAKHT BHAI</option>
    <option value="TOPI">TOPI</option>
    <option value="SHABQADAR">SHABQADAR</option>
    <option value="	PESHAWAR">PESHAWAR</option>
    <option value="PABBI">PABBI</option>
    <option value="LACHI">LACHI</option>
    <option value="TALL">TALL</option>
    <option value="BANDA DAUD SHAH">BANDA DAUD SHAH</option>
    <option value="DOMEL">DOMEL</option>
    <option value="NAURANG">NAURANG</option>
    <option value="DARABAN">DARABAN</option>
    <option value="DIR">DIR</option>
    <option value="SAMARBAGH(BARWA)">SAMARBAGH(BARWA)</option>
    <option value="ADENZAI">ADENZAI</option>
    <option value='Shalimar'>Shalimar</option>
    <option value='Raiwind'>Raiwind</option>
    <option value='Model Town'>Model Town</option>
    <option value='Lahore city'>Lahore City</option>
    <option value='Lahore Cantt'>Lahore Cantt</option>
    <option value='Dina'>Dina</option>
    <option value='Sohawa'>Sohawa</option>
    <option value='Shorkot'>Shorkot</option>
    <option value='Chunian'>Chunian</option>
    <option value='Shujabad'>Shujabad</option>
     <option value="Hala">Hala</option>
    <option value="Khairpur Nathan Shah">Khairpur Nathan Shah</option>
  <option value='Hyderabad Saddar'>Hyderabad Saddar</option>
    <option value='Jhando Mari'>Jhando Mari</option>
    <option value='North Nazimabad Town'>North Nazimabad Town</option>
    <option value='Gulshan Town'>Gulshan Town</option>
    <option value='Orangi Town'>Orangi Town</option>
    <option value='Garhi Khairo'>Garhi Khairo</option>
    <option value='Rato Dero'>Rato Dero</option>
    <option value='Khanpur'>Khanpur</option>
    <option value='Shahdadkot'>Shahdadkot</option>
    <option value='Nagarparkar'>Nagarparkar</option>
  
   <option value="Awaran">Awaran</option>
    <option value="Gishkore">Gishkore</option>
    <option value="Jhal Jhao">Jhal Jhao</option>
    <option value="Korak Jahoo">Korak Jahoo</option>
    <option value="Mashkai">Mashkai</option>
    <option value="Kalat">Kalat</option>
    <option value="Mangochar">Mangochar</option>
    <option value="Surab">Surab</option>
    <option value=" BALAKOT">Gazg</option>
    <option value="Johan">Johan</option>
     <option value="Doghoni Balghar">Doghoni Balghar</option>
    <option value="Khaplu">Khaplu</option>
    <option value="Mashabrum">Mashabrum</option>
    <option value="Gultari">Gultari</option>
    <option value="Kharmang">Kharmang</option>
    <option value="Rondu">Rondu</option>
    <option value="Shigar">Shigar</option>
    <option value="Skardu">Skardu</option>
    <option value="Astore">Astore</option>
    <option value="Shounter">Shounter</option>
  </select>