<td><label for="district">Select District:</label></td>


    <td><select name="district" class='form-control'>

    <option  disabled style='color:red'>KPK</option>    
    <option value="Abbottabad">	Abbottabad</option>
    <option value='Bannu'>Bannu</option>
    <option value='Battagram'>Battagram</option>
    <option value='Buner'>Buner</option>
    <option value='Chitral'>Chitral</option>
    <option value='Charsadda'>Charsadda</option>
    <option value='Dera Ismail Khan'>Dera Ismail Khan</option>
    <option value='Hangu'>Hangu</option>
    <option value='Haripur'>Haripur</option>
    <option value='Karak'>Karak</option>
    <option value='Kohat'>Kohat</option>
    <option value='Kolai Pallas Kohistan'>Kolai Pallas Kohistan</option>
    <option value='Upper Kohistan'>Upper Kohistan</option>
    <option value='Lower Kohistan'>Lower Kohistan</option>
    <option value='Lakki Marwat'>Lakki Marwat</option>
    <option value='Lower Dir'>Lower Dir</option>
    <option value='Malakand Protected Area'>Malakand Protected Area	</option>
    <option value='Mansehra'>Mansehra</option>
    <option value='Mardan'>Mardan</option>
    <option value='Nowshera'>Nowshera</option>
    <option value='Peshawar'>Peshawar</option>
    <option value='Swat'>Swat</option>
    <option value='Shangla'>Shangla</option>
    <option value='Swabi'>Swabi</option>
    <option value='Tank'>Tank</option>
    <option value='Upper Dir'>Upper Dir</option>
    <option value='Torghar'>Torghar</option>
     <option value="Islamabad capital territory"> Islamabad capital territory</option>
    <option  disabled style='color:red'>PUNJAB</option>
<option value='Attock'>Attock</option>
    <option value='Bahawalnagar'>Bahawalnagar</option>
    <option value='Bahawalpur'>Bahawalpurr</option>
    <option value='Bhakkar'>Bhakkar</option>
    <option value='Chakwal'>Chakwal</option>
    <option value='Chiniot'>Chiniot</option>
    <option value='Dera Ghazi Khan'>Dera Ghazi Khan</option>
    <option value='Faisalabad'>Faisalabad</option>
    <option value='Gujranwala'>Gujranwala</option>
    <option value=' Gujrat'>Gujrat</option>

    <option value='Hafizabad'>Hafizabad</option>
    <option value='Jhang'>Jhang</option>
    <option value='Jhelum'>Jhelum</option>
    <option value='Kasur'>Kasur</option>
    <option value='Khanewal'>Khanewal</option>
    <option value='Khushab'>Khushab</option>
    <option value='Lahore'>Lahore</option>
    <option value='Layyah'>Layyah</option>
    <option value='Lodhran'>Lodhran</option>
    <option value='Mandi Bahauddin'>Mandi Bahauddin</option>
    <option value='Mianwali'>Mianwali</option>    
     <option value='Multan'> Multan</option>
    <option value='Muzaffargarh'>Muzaffargarh</option>
    <option value='Narowal'>Narowal</option>
    <option value='Nankana Sahib'>Nankana Sahib</option>
    <option value='Okara'>Okara</option>
    <option value='Pakpattan'>Pakpattan</option>
     <option value='Swat'>Swat</option>
    <option value='Rahim Yar Khan'>Rahim Yar Khan</option>
    <option value='Rajanpur'>Rajanpur</option>
    <option value='Rawalpindi'>Rawalpindi</option>
    <option value='Sahiwal'>Sahiwal</option>
    <option value='Sargodha'>Sargodha</option>
     <option value='Sheikhupura'>Sheikhupura</option>
    <option value='Sialkot'> Sialkot</option>
    <option value='Toba Tek Singh'>Toba Tek Singh</option>
    <option value='Vehari'>Vehari</option>

    <option  disabled style='color:red'>SINDH</option>    
    <option value="Badin">Badin</option>
    <option value='Dadu'>Dadu</option>
    <option value='Ghotki'> Ghotki</option>
    <option value='Hyderabad'>Hyderabad</option>
    <option value='Jacobabad'>Jacobabad</option>
    <option value='Jamshoro'>Jamshoro</option>
    <option value='Karachi Central'>Karachi Central</option>
    <option value='Kashmore'>Kashmore </option>
    <option value='Khairpur'>Khairpur</option>
    <option value='Larkana'>Larkana</option>
    <option value=' Matiari'>Matiari</option>
    <option value='Mirpur Khas'>Mirpur Khas</option>
    <option value='Naushahro Firoze'>Naushahro Firoze</option>
    <option value='Shaheed Benazirabad'>Shaheed Benazirabad</option>
    <option value='Qambar Shahdadkot'>Qambar Shahdadkot</option>
    <option value='Sanghar'>Sanghar</option>
    <option value='Shikarpur'>Shikarpur</option>
    <option value='Sukkur'>Sukkur</option>
    <option value='Tando Allahyar'>Tando Allahyar</option>
    <option value='Tando Muhammad Khan'>Tando Muhammad Khan</option>
    <option value="Tharparkar">Tharparkar</option>
    <option value='Thatta'>Thatta</option>
    <option value='Umerkot'>Umerkot</option>
    <option value='Sujawal'>Sujawal</option>
    <option value='Karachi East'>Karachi East</option>
    <option value='Karachi South'>Karachi South</option>
    <option value='Karachi West'>Karachi West</option>
    <option value='Korangi'>Korangi</option>
    <option value='Malir'>Malir</option>

     <option  disabled style='color:red'>Balochistan</option>    
    <option value="Awaran">Awaran</option>
    <option value='Barkhan'>Barkhan</option>
    <option value='Kachhi'>Kachhi</option>
    <option value='Chagai'>Chagai</option>
    <option value='Dera Bugti'>Dera Bugti</option>
    <option value='Gwadar'>Gwadar</option>
    <option value='Harnai'>Harnai</option>
    <option value='Jafarabad'>Jafarabad</option>
    <option value='Jhal Magsi'>Jhal Magsi</option>
    <option value='Kalat'>Kalat</option>
    <option value='Kech'>Kech</option>
    <option value='Kharan'>Kharan</option>
    <option value='Kohlu'>Kohlu</option>
    <option value='Khuzdar'>Khuzdar</option>
    <option value='Killa Abdullah'>Killa Abdullah</option>
    <option value='Killa Saifullah'>Killa Saifullah</option>
    <option value='Lasbela'>Lasbela</option>
    <option value='Loralai'>Loralai</option>
    <option value='Mastung'>Mastung</option>
    <option value='Musakhel'>Musakhel</option>
    <option value='Nasirabad'>Nasirabad</option>
    <option value='Nushki'>Nushki</option>
    <option value='Panjgur'>Panjgur</option>
    <option value='Pishin'>Pishin</option>
    <option value='Quetta'>Quetta</option>
    <option value='Sherani'>Sherani</option>
    <option value='Sibi'>Sibi</option>
    <option value="Washuk">Washuk</option>
    <option value='Zhob'>Zhob</option>
    <option value='Ziarat'>Ziarat</option>
    <option value='Lehri'>Lehri</option>
    <option value='Sohbatpur'>Sohbatpur</option>
    <option value='Shaheed Sikandarabad'>Shaheed Sikandarabad</option>
    <option value='Duki'>Duki</option>

     <option  disabled style='color:red'>GILGIT BALTISTAN</option>    
    <option value="Ghanche">Ghanche</option>
    <option value='Skardu'>Skardu</option>
    <option value='Shigar'>Shigar</option>
    <option value='Kharmang'>Kharmang</option>
    <option value='Ghizer'>Ghizer</option>
    <option value='Gilgit'>Gilgit</option>
    <option value=' Hunza'>Hunza</option>
    <option value='Nagar'>Nagar</option>
    <option value='Astore'>Astore</option>
    <option value='Diamer'>Diamer</option>
    
    
  </select></td>
